### Admin Login
POST http://localhost:4000/admin-api/login
Content-Type: application/json

{
  "admin_id": "ravi",
  "password": "ravi@infrastructure"
}

###View all complaints
GET http://localhost:4000/admin-api/view-complaints

###
GET http://localhost:4000/admin-api/view-complaint/1739972132293

### Get Complaints Count
GET http://localhost:4000/admin-api/complaints-count/Transport

### Update complaint status(Pending → In Progress → Resolved)
PUT http://localhost:4000/admin-api/update-status/1740184025030
Content-Type: application/json

{
    "status": "Resolved"
}

### Delete a complaint
DELETE http://localhost:4000/admin-api/delete-complaint/C1003


### Filter complaints (Category filter)
GET http://localhost:4000/admin-api/filter-complaints?category=Transport
Accept: application/json

### Filter complaints (Status filter)
GET http://localhost:4000/admin-api/filter-complaints?status=Resolved
Accept: application/json

### Filter complaints (Weekly)
GET http://localhost:4000/admin-api/filter-complaints?dateRange=weekly
Accept: application/json

### Filter complaints (Monthly)
GET http://localhost:4000/admin-api/filter-complaints?dateRange=monthly
Accept: application/json

### COmment on Complaint
PUT http://localhost:4000/admin-api/complaints/C1005/comment
Content-Type: application/json

{
  "comment": "We will investigate this issue soon."
}



